"""Telegram MCP server assembly and public entrypoint."""

from __future__ import annotations

from .telethon_compat import apply_telethon_compat

apply_telethon_compat()

from . import resources as _resources  # noqa: F401 — registers MCP resources at import

from .runtime import (
    get_tg,
    lifespan,
    mcp,
    read_port,
    read_transport,
    run_server,
    shared_mode_enabled,
)
from .tools import (
    add_contact,
    create_channel,
    create_group,
    create_poll,
    delete_chat_photo,
    delete_contact,
    delete_messages,
    delete_profile_photo,
    demote_admin,
    doctor_check,
    download_media,
    download_media_batch,
    download_story_media,
    edit_chat_title,
    edit_message,
    export_story_link,
    forward_messages,
    global_search,
    get_blocked_users,
    get_chat_info,
    get_discussion_message,
    get_forum_topics_by_id,
    get_invite_link,
    get_me,
    get_message_link,
    get_message_reactions,
    get_participants,
    get_peer_stories,
    get_pinned_messages,
    get_pinned_stories,
    get_stories_archive,
    get_stories_by_id,
    get_story_viewers,
    get_story_views,
    get_thread_replies,
    get_unread_reactions,
    get_user_photos,
    get_user_status,
    health_check,
    import_contacts,
    invite_to_group,
    leave_chat,
    list_chats,
    list_contacts,
    list_forum_topics,
    list_messages,
    mark_as_read,
    collect_context,
    collect_dialog_context,
    draft_reply,
    download_dialog_media,
    prepare_dialog_reply,
    prepare_reply_message,
    prepare_send_message,
    prepare_media_inspection_manifest,
    find_dialog,
    promote_admin,
    read_dialog,
    read_dialog_slice,
    read_dialog_by_date,
    read_recent_dialog,
    read_today_dialog,
    register_all_tools,
    reply_in_dialog,
    reply_message,
    reply_to_message,
    resolve_dialog,
    resolve_username,
    search_dialog_messages,
    search_contacts,
    search_messages,
    search_public_chats,
    sent_media_search,
    telegram_confirmed_send,
    telegram_count_documents,
    telegram_count_photos,
    telegram_count_pinned,
    telegram_count_posts,
    telegram_count_videos,
    telegram_count_voice,
    telegram_dialog_metadata,
    telegram_inspect_media,
    telegram_get_message,
    telegram_latest_message,
    telegram_prepare_reply,
    telegram_read,
    telegram_search,
    send_file,
    send_dialog_message,
    send_message,
    send_message_with_buttons,
    send_reaction,
    send_voice,
    set_chat_archived,
    set_chat_muted,
    set_user_banned,
    set_message_pinned,
    set_user_blocked,
    transcribe_voice,
    update_profile,
)

register_all_tools(mcp)
